# Generated by Django 4.2.16 on 2024-10-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_follow"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_private",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
