# Generated by Django 4.2.16 on 2024-10-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(default=1, upload_to="media/post_image"),
            preserve_default=False,
        ),
    ]
