# Generated by Django 4.2.16 on 2024-10-16 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_post_image_like_dislike"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="replied_to",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="blog.post"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="post_image/"),
        ),
    ]
