# Generated by Django 4.2.16 on 2024-10-21 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_alter_profile_is_private"),
        ("blog", "0007_remove_post_image_alter_post_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dislike",
            name="user",
        ),
        migrations.RemoveField(
            model_name="like",
            name="user",
        ),
        migrations.RemoveField(
            model_name="post",
            name="user",
        ),
        migrations.AddField(
            model_name="dislike",
            name="profile",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.profile",
            ),
        ),
        migrations.AddField(
            model_name="like",
            name="profile",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.profile",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="profile",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.profile",
            ),
        ),
    ]
